### PR TITLE
Add ability to probe TLS behind SMTP STARTTLS (NX-2455)

### PR DESCRIPTION
**Pull request by andrey-utkin**
This implements probing TLS behind SMTP STARTTLS, as described in https://track.radensolutions.com/issue/NX-2455 .

A trivial testing script is added.

Potential future work:

- support of protocols other than SMTP;

- automated local setup of https://github.com/chromium/badssl.com for
  testing;

- expand badssl.com test suite with SMTP/STARTTLS services;

- add an overall "health" TLS.Certificate metric:
  for many badssl.com cases there's no clear way to demonstrate that
  they are bad with existing TLS.Certificate.*.
  NetworkService.TLSStatus() also doesn't give expected results.

### CODE REVIEW

**Review by 2128506 — CHANGES_REQUESTED** [review]

**Comment by andrey-utkin** [comment]
Requested changes applied, squashed into the first commit.

```diff
--- a/src/agent/subagents/netsvc/tls.cpp
+++ b/src/agent/subagents/netsvc/tls.cpp
@@ -294,12 +294,10 @@ LONG H_TLSCertificateInfo(const TCHAR *parameters, const TCHAR *arg, TCHAR *valu

    if (!AgentGetParameterArgA(parameters, 1, host, sizeof(host)) ||
        !AgentGetParameterArg(parameters, 2, portText, sizeof(portText) / sizeof(TCHAR)) ||
-       !AgentGetParameterArgA(parameters, 3, sniServerName, sizeof(sniServerName)))
+       !AgentGetParameterArgA(parameters, 3, sniServerName, sizeof(sniServerName))
+       !AgentGetParameterArgA(parameters, 4, startTlsInProto, sizeof(startTlsInProto)))
       return SYSINFO_RC_UNSUPPORTED;

-   // optional arg
-   AgentGetParameterArgA(parameters, 4, startTlsInProto, sizeof(startTlsInProto));
-
    if (host[0] == 0 || portText[0] == 0)
    {
       nxlog_debug_tag(DEBUG_TAG, 7, _T("H_TLSCertificateInfo: invalid host/port combination \"%hs\"/\"%s\""), host, portText);
@@ -327,7 +325,7 @@ LONG H_TLSCertificateInfo(const TCHAR *parameters, const TCHAR *arg, TCHAR *valu
       return SYSINFO_RC_ERROR;
    }

-   if (strlen(startTlsInProto)) {
+   if (startTlsInProto[0] != '\0') {
       bool startTlsSuccess = SetupStartTLSSession(hSocket, timeout, (sniServerName[0] != 0) ? sniServerName : host, startTlsInProto);
       if (!startTlsSuccess) {
          nxlog_debug_tag(DEBUG_TAG, 7, _T("H_TLSCertificateInfo(%hs, %d): STARTTLS error"), host, port);

```

**Comment by 2128506** [comment]
There is compilation error, because of missing || after !AgentGetParameterArgA(parameters, 3, sniServerName, sizeof(sniServerName))

**Review by 2128506 — APPROVED** [review]
Looks good. Do you plan to add pop3 and imap support in this PR or in separate one?

**Comment by andrey-utkin** [comment]
I don't care much which way, but merging this chunk now seems better.

I will follow up with POP3 and IMAP support.

**Pull request merged**
