### PR TITLE
NX-2488: enable use of web service cache in requests from NXSL

### PR DESCRIPTION
**Pull request by andrey-utkin**
The code for using cached results was copied from QueryWebService().
This led to a lot of curl API using code to be dropped, for which I am a
bit worried that I might have overlooked some feature buried in it.

This suggests that QueryWebService() and WebServiceCustomRequest() could
benefit from a lot of code reuse.

An automated test was added: run tests/nx-2488/test-websvc-caching on a
fresh disposable install configured to use SQLite.

### CODE REVIEW

**Comment by andrey-utkin** [comment]
Sorted out compilation warnings:

```
websvc.cpp: In function ‘void WebServiceCustomRequest(NXCPMessage*, std::shared_ptr<AbstractCommSession>)’:
websvc.cpp:1001:12: warning: unused variable ‘followLocation’ [-Wunused-variable]
 1001 |       bool followLocation = request->getFieldAsBoolean(VID_FOLLOW_LOCATION);
      |            ^~~~~~~~~~~~~~
websvc.cpp:1003:16: warning: unused variable ‘requestTimeout’ [-Wunused-variable]
 1003 |       uint32_t requestTimeout = request->getFieldAsUInt32(VID_TIMEOUT);
      |                ^~~~~~~~~~~~~~
websvc.cpp:1004:19: warning: unused variable ‘requestMethod’ [-Wunused-variable]
 1004 |       const char *requestMethod = s_httpRequestMethods[requestMethodCode];
      |                   ^~~~~~~~~~~~~
```

**Comment by 2128506** [comment]
I see few issues with this change:
1. It seems that HTTP response code is no longer returned to the server for direct request (was message filed VID_WEBSVC_RESPONSE_CODE).
2. What if option for caching custom requests is not set? I don't see how agent side code will bypass cache in that case.
3. Original query web service code was intended for data collection only and expects 2xx response, anything else will be interpreted as error. Custom requests should return whatever data is returned by web server also for 4xx and 5xx (it is usual for various web APIs for example to return 400 and JSON document with detailed error information).

**Comment by 2128506** [comment]
Also, custom request should not attempt to interpret/parse response body, just store it in cache if requested and return to caller.

**Comment by andrey-utkin** [comment]
Thanks for review.

>     1. It seems that HTTP response code is no longer returned to the server for direct request (was message filed VID_WEBSVC_RESPONSE_CODE).

Addressed: https://github.com/andrey-utkin/netxms/commit/dcf892b5991586d313218cfa267314af3a7297b4
(squashed into single commit in this PR)

>     2. What if option for caching custom requests is not set? I don't see how agent side code will bypass cache in that case.

Perhaps we shouldn't add any such boolean parameter here.

There is already "Cache retention time" parameter which takes positive integer values.
It is already presented in nxmc GUI as of 5.0.3 release.
The default value is 0 and the math works out so that it effectively disables caching. I was going to add that checkbox before I noticed there is already this parameter.

>     3. Original query web service code was intended for data collection only and expects 2xx response, anything else will be interpreted as error. Custom requests should return whatever data is returned by web server also for 4xx and 5xx (it is usual for various web APIs for example to return 400 and JSON document with detailed error information).

Addressed: https://github.com/andrey-utkin/netxms/commit/7fe5e746bf2ecc62dcd31b3a097cc436b9f09e72
(squashed into single commit in this PR)

> Also, custom request should not attempt to interpret/parse response body, just store it in cache if requested and return to caller.

Could you please point this out in code? I don't see where my code is doing that.

**Comment by 2128506** [comment]
My only concern regarding last change is that cache indicator should be first argument. Usually in those (quite rare) cases when we use named function arguments in NXSL they are not position-bound. You can looks at them as on options in Linux command line tool: you can place --option in any position in command line, and it will not affect position-based parameters. Maybe it is a good idea to add helper class or function for NXSL function arguments that will rearrange named and positional arguments for simplified access (similar to what getopt() do).
Also, I'd probably name this argument simply "cache" - I suppose it is called "acceptCached" because it allows reuse of already cached content, but it is also an instruction to agent if retrieved content should be cached or not.

**Comment by andrey-utkin** [comment]
As discussed in a meeting, I've left the new parameter as it was, and worked on adding flexibility of named parameter positioning.

I haven't achieved complete flexibility yet, as the first two args (webservice name and request method) are handled in another function. It's going to be messy as it would impact both `Node::callWebService()` and `BaseWebServiceRequestWith???Data()` and both would have to become more complex to handle more cases. That is unless we do the getopt-style tooling.

So for now these are the options I see:
- keep this open until we implement complete position flexibility;
- take the current version, in which the named param must go after the request method but then has the flexibility;
- drop the last feature commit and take the verison in which the new named parameter must go after all the existing positional parameters.

**Comment by andrey-utkin** [comment]
I've just realised a problem with the implemented approach: it just caches all request methods, HEAD, GET, POST, DELETE etc. If I recall correctly, in a meeting it was suggested to cache GET (perhaps HEAD could be treated the same), but not any other methods. I can rework this.

Also it would make sense to follow directionally https://www.rfc-editor.org/rfc/rfc7234#section-4.4 and make it so that POST/UPDATE/DELETE etc would _invalidate_ the cache.

**Comment by 2128506** [comment]
Yes, that's correct. Please rework as suggested.

**Comment by 2128506** [comment]
Squashed and merged into master

**Pull request closed without merging**
