### PR TITLE
NX-2517: handle sparse CPU cores information, changes in the set

### PR DESCRIPTION
**Pull request by andrey-utkin**
This addresses https://track.radensolutions.com/issue/NX-2517 .

The first commit avoids the crash when under rr or with some cores manually disabled.

The subsequent few commits rework entire "CPU stats collection" in src/agent/subagents/linux/cpu.cpp into C++, to avoid manual memory and ring buffer management of a changing set of CPUs - they can appear and go at different times.

Since it's a risky change, there are functional and unit tests. Unit test was in particular motivated by suspicious valgrind reports from the functional test [valgrind.out.gz](https://github.com/netxms/netxms/files/15172151/valgrind.out.gz) which I so far couldn't track down. The unit test shows no problems under valgrind.

The last commit, "subagent: linux, freebsd: add System.CPU.Usage5.Idle(*)" fixes a peculiar irregularity in metrics naming which was discovered while writing the tests.

-------------------
Original description of a draft PR from early April:

One of the commits introduces stricter locking for reading the stored measurements. This might be considered overkill, but since it was planned to handle possibly growing set of CPU cores, it is inevitable to have some locking, because otherwise the reader might be reading a memory "table" which is disused by that time. If this is shown to cause significant performance regression, I will look into that.

One of the commits is a rewrite of the code of `CPU.Usage*` metrics collection and serving into a more "semantic" C++, using more high-level standard containers to take care of memory management to avoid having to take care of tricky combination of cases.

This PR is draft for now since I haven't tested changing the set of CPU cores at runtime, but I want to get team's feedback on the approach taken.

### CODE REVIEW

**Comment by 2128506** [comment]
It looks to be a bit overkill on locking. There is no point to lock mutex around reading / updating boolean variable or single integer variable. It is guaranteed that 32 bit integer (64 bit on 64 bit system) will be updated atomically (so you won't get garbage as a value), and actual order of reading and writing is not relevant. Locking on start and stop is not necessary because other threads will not access data via metric handlers at this point.
Regarding rewriting CPU usage code in more C++ style - I'm ok with that if this will clean up the code and make it easier to maintain. This is very old part of the system, it definitely can benefit from refactoring.

**Comment by andrey-utkin** [comment]
>It looks to be a bit overkill on locking. There is no point to lock mutex around reading / updating boolean variable or single integer variable. It is guaranteed that 32 bit integer (64 bit on 64 bit system) will be updated atomically (so you won't get garbage as a value), and actual order of reading and writing is not relevant. Locking on start and stop is not necessary because other threads will not access data via metric handlers at this point.
The concerns for which I introduced locking are:

- the moment of growing the tables upon detecting higher indexes of CPU cores. What would you suggest to ensure reads of freed or disused tables don't happen?

- the problem of stale reads and non-propagated writes of non-volatile variables.

**Comment by 2128506** [comment]
> It looks to be a bit overkill on locking. There is no point to lock mutex around reading / updating boolean variable or single integer variable. It is guaranteed that 32 bit integer (64 bit on 64 bit system) will be updated atomically (so you won't get garbage as a value), and actual order of reading and writing is not relevant. Locking on start and stop is not necessary because other threads will not access data via metric handlers at this point.
> The concerns for which I introduced locking are: - the moment of growing the tables upon detecting higher indexes of CPU cores. What would you suggest to ensure reads of freed or disused tables don't happen? - the problem of stale reads and non-propagated writes of non-volatile variables.

I'm only talking about read access to single integers. Of course, locks are needed when accessing data from CPU tables that can be deleted or being changed when other thread attempts to read them.
This code for example:
   m_cpuUsageMutex.lock();
   ret_uint(pValue, m_maxCPU);
   m_cpuUsageMutex.unlock();
m_maxCPU cannot contain garbage, as we are guaranteed that integer value read or write is atomic (in a sense that reader will get either old value or new value, and not part of old value and part of new value). In worst case reader will get value that was valid few milliseconds ago - but this is fine, it is network call anyway, and this situation is no different from when network request to read this value comes few milliseconds earlier.

This is mostly theoretical discussion of course - as reads happens much less often than updates to CPU stats, it will not really impact performance - just makes code a bit harder to read and follow IMHO.

**Comment by andrey-utkin** [comment]
> > It looks to be a bit overkill on locking. There is no point to lock mutex around reading / updating boolean variable or single integer variable. It is guaranteed that 32 bit integer (64 bit on 64 bit system) will be updated atomically (so you won't get garbage as a value), and actual order of reading and writing is not relevant. Locking on start and stop is not necessary because other threads will not access data via metric handlers at this point.
> > The concerns for which I introduced locking are: - the moment of growing the tables upon detecting higher indexes of CPU cores. What would you suggest to ensure reads of freed or disused tables don't happen? - the problem of stale reads and non-propagated writes of non-volatile variables.

> I'm only talking about read access to single integers. Of course, locks are needed when accessing data from CPU tables that can be deleted or being changed when other thread attempts to read them.

I see now. I anticipated that locking for reading even the tables would be a hard sell and raise objections.

> This code for example: 
```c
m_cpuUsageMutex.lock();
ret_uint(pValue, m_maxCPU);
m_cpuUsageMutex.unlock();
```
> m_maxCPU cannot contain garbage, as we are guaranteed that integer value read or write is atomic (in a sense that reader will get either old value or new value, and not part of old value and part of new value).

True.

> In worst case reader will get value that was valid few milliseconds ago

I agree it would be, if this variable was volatile. For non-volatile, the serving thread is long-lived / recycled, the stale read may persist for long time. It may not, if the thread hits some other memory barriers - but I am not sure about what they are.

Also the C++ rewrite changed that code into 
```c
   m_cpuUsageMutex.lock();
   ret_uint(pValue, collector->m_perCore.size());
   m_cpuUsageMutex.unlock();
```

Part of the approach in the "enforce strict locking" commit is to set a simple rule which is easy to check. I accept that some mutex use could possibly be removed.

Thanks for the feedback overall, I feel encouraged.
I will write tests which perturb the CPU set and share them there.

**Comment by 2128506** [comment]
> > In worst case reader will get value that was valid few milliseconds ago
> 
> I agree it would be, if this variable was volatile. For non-volatile, the serving thread is long-lived / recycled, the stale read may persist for long time. It may not, if the thread hits some other memory barriers - but I am not sure about what they are.

This is where my knowledge is not enough - I don't know if old value may persist for significant time. Processing threads do lot of other locks though, so likely they will hit another memory barrier soon enough.

Also, for code simplicity, you can use LockGuard class (same semantics as std::lock_guard) when lock is needed until the end of code block. Probably std::lock_guard will work too, as our Mutex class conforms to BasicLockable requirements.

**Comment by 2128506** [comment]
Squashed and merged into master

**Pull request closed without merging**
