### PR TITLE
Add the ability to query table dci history values

### PR DESCRIPTION
**Pull request by mishaal79**
Added the ability to query history values for table DCI using the `"/objects/{object-id}/datacollection/{id}/values"` endpoint.

Example response is below,
- A collection of dictionaries  against key `"values"` is used to represent rows of a table 
```
{
    "values":[
       {
          "Column1":{
             "nodeId":11962,
             "dciId":42791,
             "dataType":"STRING",
             "values":[
                {
                   "timestamp":1633914879,
                   "value":"value1"
                }
             ]
          },
          "Column2":{
             "nodeId":11962,
             "dciId":42791,
             "dataType":"STRING",
             "values":[
                {
                   "timestamp":1633914879,
                   "value":"test"
                }
             ]
          }
       },
       {
          "Column1":{
             "nodeId":11962,
             "dciId":42791,
             "dataType":"STRING",
             "values":[
                {
                   "timestamp":1633914879,
                   "value":"value2"
                }
             ]
          },
          "Column2":{
             "nodeId":11962,
             "dciId":42791,
             "dataType":"STRING",
             "values":[
                {
                   "timestamp":1633914879,
                   "value":"test"
                }
             ]
          }
       }
    ]
 } 
```

### CODE REVIEW

**Comment by benletchford** [comment]
Hey, @2128506 any chance we could get your thoughts on this? We need this for some of the integrations we've started using.

**Comment by 2128506** [comment]
Hi,
I think I will be able to look into it next week.
Best regards,Victor

**Comment by benletchford** [comment]
Thanks Victor :)

**Comment by 2128506** [comment]
Hi,
this approach will work, however it is very ineffective - API will send history request for each cell in a table. Each such request will read table values from database, again and again. So for large tables it will be quite heavy operation. I think that better approach would be to add new API call that will return array of Table objects for given time period - that way one SQL query will be enough. I can add such API call so you won't need to make server side changes.

**Comment by mishaal79** [comment]
Hey,
okay got it.
Please proceed with adding new API call to the backend and I shall modify the Web API code to use it.
:)

**Comment by 2128506** [comment]
I have updated Java API (it is in master branch and in stable-3.10). Now when you call NXCSession.getCollectedData on table DCI with data type set to HistoricalDataType.FULL_TABLE, retrieved data rows in DciData object will contain table objects.

Example in nxshell:
```python
data = session.getCollectedData(213, 1078, None, None, 100, HistoricalDataType.FULL_TABLE)
print(data)
for v in data.values:
    print(v)
```
This script retrieves and prints last 100 values for table DCI with ID 1078 on node with ID 213.

Best regards,
Victor

**Comment by 2128506** [comment]
Hello!
Could you please show sample output of table DCI data request?

**Comment by mishaal79** [comment]
> 
> 
> Hello! Could you please show sample output of table DCI data request?

Hello Victor,

The sample JSON response looks like below for a table with two columns and two rows,
Each item within `data: []` represents a row of the table

```JSON
{
    "values":{
       "nodeId":12,
       "dciId":213,
       "dataType":"INT32",
       "source":"SNMP",
       "title":"General Table DCI",
       "columns":[
          {
             "Name":"COL1",
             "instanceColumn":true,
             "dataType":"STRING"
          },
          {
             "Name":"COL2",
             "instanceColumn":false,
             "dataType":"INT32"
          }
       ],
       "data":[
          {
             "COL1":[
                {
                   "value":"device1",
                   "timestamp":11111
                },
                {
                   "value":"device1",
                   "timestamp":11112
                },
                {
                   "value":"device1",
                   "timestamp":11113
                }
             ],
             "COL2":[
                {
                   "value":"102",
                   "timestamp":11111
                },
                {
                   "value":"101",
                   "timestamp":11112
                },
                {
                   "value":"99",
                   "timestamp":11113
                }
             ]
          },
          {
             "COL1":[
                {
                   "value":"device2",
                   "timestamp":11111
                },
                {
                   "value":"device2",
                   "timestamp":11112
                },
                {
                   "value":"device2",
                   "timestamp":11113
                }
             ],
             "COL2":[
                {
                   "value":"100",
                   "timestamp":11111
                },
                {
                   "value":"101",
                   "timestamp":11112
                },
                {
                   "value":"99",
                   "timestamp":11113
                }
             ]
          }
       ]
    }
 }
```

**Comment by 2128506** [comment]
Did you consider moving timestamp to upper level? It is pointless to have timestamp set for each cell or even for each row - it always the same. Data could be array of objects like this:
```json
"data":[
   {
      "timestamp":11111,
      "value":
      {
         "COL1":["100", "101", "102"],
         "COL2":["200", "201", "202"]
      }
   },
   {
      "timestamp":11122,
      "value":
      {
         "COL1":["100", "101", "102"],
         "COL2":["200", "201", "202"]
      }
   }
]
```
or organized in rows:
```json
"data":[
   {
      "timestamp":11111,
      "value":
      [
         { "COL1":"100", "COL2":"200" },
         { "COL1":"101", "COL2":"201" },
         { "COL1":"102", "COL2":"202" }
      ]
   },
   {
      "timestamp":11122,
      "value":
      [
         { "COL1":"100", "COL2":"200" },
         { "COL1":"101", "COL2":"201" },
         { "COL1":"102", "COL2":"202" }
      ]
   }
]
```
This should remove lot of redundant information for large tables and/or large number of retrieved values.

Best regards,
Victor

**Comment by mishaal79** [comment]
Hello Victor,

I did consider having the timestamp on a upper level.
The rationale for laying out the timestamp for each cell is considering how the Table DCI history values are represented in NXMC and this is how I expect to consume it through the Web API too.

**Example Table**

image

**Example History Values in for cell in table**

image

With regard to your concern of having redundant data for large tables, I reckon the response can be gzip compressed.

Best Regards,
Mishal

**Comment by benletchford** [comment]
Hi @2128506 , I'm guessing you're not keen on merging this in its current state?

If we changed it to be as you described above, would you be happy to merge in?

Thanks, Ben

**Comment by 2128506** [comment]
Hi,
sorry for late reply! In my opinion these are two separate cases - when you need history values for specific cell and when you need history as table objects. Now we have Java API calls for both options, and maybe we should have additional option(s) for values endpoint - if no options are given, then it return series of table objects in more compact form, and if column name and instance are provided then it return history for specific cell. We can also make verbose form for full tables (the one that you are proposing) as an output option along with more compact forms if that helps consuming data in certain cases.
Best regards,
Victor

**Comment by 2128506** [comment]
I have modified code a bit - now it can generate output in 3 forms, selected by parameter outputFormat: InstanceColumnRow (your original format), ColumnRow (output grouped by columns then rows), RowColumn (output grouped by rows then columns). I also removed one unnecessary level in output document - it always contained "values" property which contained all the data. Now everything from this "values" object moved to root object. I also added pseudo-column named "__instance" that contains instance key for the row.
All changes merged into master, 3.10, and 3.9 branches.
Best regards,
Victor

**Comment by mishaal79** [comment]
Thanks Victor, great work and appreciate it.

regards,
Mishal

**Pull request merged**
